version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../backend:/app
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json
      - GOOGLE_CLOUD_PROJECT=your-project-id
    depends_on:
      - frontend

  frontend:
    build:
      context: ../frontend
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
